### ISSUE TITLE
UML do Projecto

### ISSUE THREAD

**Issue by FMCalisto** [lidiamcfreitas/po-project#1]
Olá Lídia!

Tens aqui o UML do Projecto de PO?

**Comment by lidiamcfreitas** [comment]
Hey!
Não, o projecto aqui está incompleto. **Vou pedir** ao prof. David Matos o projecto, pode ser que tenha e que esteja lá o UML. Depois digo-te algo.

**Comment by lidiamcfreitas** [comment]
Sorry,
diz que só dá no final do semestre.
